name: sadsac83
favicon: null
layout_spectrum: 0.5544636533595622
typography_spectrum: 0.7524683594238013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e0e7'
    - '#10151b'
    - '#909da6'
    - '#32373d'
    - '#9c7d46'
  brandStrength: 0.7952323299832642
  lightness: 0.3937055205460638
  saturation: 0.15595332463271916
  rhythmicContrast: 0.6895493385381997
purpose: []
